Remove deprecated RESTORE_DEVICE_STATE_ON_STARTUP

diff --git a/func.d/30-tlp-func-rf-sw b/func.d/30-tlp-func-rf-sw
--- a/func.d/30-tlp-func-rf-sw
+++ b/func.d/30-tlp-func-rf-sw
@@ -372,117 +372,97 @@ set_radio_device_states () {
     local dev devs2disable devs2enable restore
     local quiet=0
 
-    if wordinlist "$1" "start stop" && [ "${RESTORE_DEVICE_STATE_ON_STARTUP}" = "1" ]; then
-        # save/restore mode on system startup/shutdown (DEPRECATED)
-        echo_debug "rf" "set_radio_device_states($1).restore"
-        case "$1" in
-            start)
-                if restore_device_states; then
-                    echo "Radio device states restored."
-                else
-                    echo "No saved radio device states found."
+    # disable/enable on system startup/shutdown or profile select
+    case "$1" in
+        start) # system startup
+            devs2disable="$DEVICES_TO_DISABLE_ON_STARTUP"
+            devs2enable="$DEVICES_TO_ENABLE_ON_STARTUP"
+            ;;
+
+        stop) # system shutdown
+            devs2disable=""
+            devs2enable=""
+
+            if [ "$X_WIFI_ON_SHUTDOWN" != "0" ]; then
+                # NM workaround: if
+                # 1. disable wifi is configured somehow, and
+                # 2. wifi is not explicitly configured for shutdown
+                # then re-enable wifi on shutdown to prepare for startup
+                if wordinlist "wifi" "$DEVICES_TO_DISABLE_ON_BAT
+                                        $DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE
+                                        $DEVICES_TO_DISABLE_ON_LAN_CONNECT
+                                        $DEVICES_TO_DISABLE_ON_WIFI_CONNECT
+                                        $DEVICES_TO_DISABLE_ON_WWAN_CONNECT" && \
+                    ! wordinlist "wifi" "$devs2disable $devs2enable"; then
+                    devs2enable="wifi $devs2enable"
                 fi
-                ;;
+            fi
+            ;;
 
-            stop)
-                # shellcheck disable=SC2119
-                save_device_states
-                echo "Radio device states saved."
-                ;;
-        esac
-    else
-        # disable/enable on system startup/shutdown or profile select
-        case "$1" in
-            start) # system startup
-                devs2disable="$DEVICES_TO_DISABLE_ON_STARTUP"
-                devs2enable="$DEVICES_TO_ENABLE_ON_STARTUP"
-                ;;
+        "$PP_PRF") # performance profile --> build enable list
+            quiet=1 # do not display progress
+            devs2enable="${DEVICES_TO_ENABLE_ON_AC:-}"
+            devs2disable=""
+            ;;
 
-            stop) # system shutdown
-                devs2disable=""
-                devs2enable=""
+        "$PP_BAL"|"$PP_SAV") # balanced/power-saver profile --> build disable list
+            quiet=1 # do not display progress
+            devs2enable=""
+            devs2disable="${DEVICES_TO_DISABLE_ON_BAT:-}"
 
-                if [ "$X_WIFI_ON_SHUTDOWN" != "0" ]; then
-                    # NM workaround: if
-                    # 1. disable wifi is configured somehow, and
-                    # 2. wifi is not explicitly configured for shutdown
-                    # then re-enable wifi on shutdown to prepare for startup
-                    if wordinlist "wifi" "$DEVICES_TO_DISABLE_ON_BAT
-                                          $DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE
-                                          $DEVICES_TO_DISABLE_ON_LAN_CONNECT
-                                          $DEVICES_TO_DISABLE_ON_WIFI_CONNECT
-                                          $DEVICES_TO_DISABLE_ON_WWAN_CONNECT" && \
-                       ! wordinlist "wifi" "$devs2disable $devs2enable"; then
-                        devs2enable="wifi $devs2enable"
-                    fi
-                fi
-                ;;
+            # check configured list for connected devices
+            for dev in ${DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE:-}; do
+                # if device is not connected and not in list yet --> add to disable list
+                { case $dev in
+                    bluetooth) any_bluetooth_in_use ;;
+                    nfc) any_nfc_in_use ;;
+                    wifi) any_wifi_in_use ;;
+                    wwan) any_wwan_in_use ;;
+                esac } || wordinlist "$dev" "$devs2disable" || devs2disable="$dev $devs2disable"
+            done
+            devs2disable="${devs2disable# }"
+            ;;
 
-            "$PP_PRF") # performance profile --> build enable list
-                quiet=1 # do not display progress
-                devs2enable="${DEVICES_TO_ENABLE_ON_AC:-}"
-                devs2disable=""
-                ;;
+    esac
 
-            "$PP_BAL"|"$PP_SAV") # balanced/power-saver profile --> build disable list
-                quiet=1 # do not display progress
-                devs2enable=""
-                devs2disable="${DEVICES_TO_DISABLE_ON_BAT:-}"
+    echo_debug "rf" "set_radio_device_states($1): enable=$devs2enable disable=$devs2disable"
 
-                # check configured list for connected devices
-                for dev in ${DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE:-}; do
-                    # if device is not connected and not in list yet --> add to disable list
-                    { case $dev in
-                        bluetooth) any_bluetooth_in_use ;;
-                        nfc) any_nfc_in_use ;;
-                        wifi) any_wifi_in_use ;;
-                        wwan) any_wwan_in_use ;;
-                    esac } || wordinlist "$dev" "$devs2disable" || devs2disable="$dev $devs2disable"
-                done
-                devs2disable="${devs2disable# }"
-                ;;
+    # disable configured radios
+    if [ -n "$devs2disable" ]; then
+        [ "$quiet" = "1" ] || printf "Disabling radios:"
+        for dev in bluetooth nfc wifi wwan; do
+            if wordinlist "$dev" "$devs2disable"; then
+                [ "$quiet" = "1" ] || printf ' %s' "$dev"
+                device_switch $dev off
+            fi
+        done
+        [ "$quiet" = "1" ] || echo "."
+    fi
 
-        esac
-
-        echo_debug "rf" "set_radio_device_states($1): enable=$devs2enable disable=$devs2disable"
-
-        # disable configured radios
-        if [ -n "$devs2disable" ]; then
-            [ "$quiet" = "1" ] || printf "Disabling radios:"
+    # enable configured radios
+    if [ -n "$devs2enable" ]; then
+        if [ "$1" = "radiosw" ]; then
+            # radiosw mode: disable radios not listed
             for dev in bluetooth nfc wifi wwan; do
-                if wordinlist "$dev" "$devs2disable"; then
-                    [ "$quiet" = "1" ] || printf ' %s' "$dev"
+                if ! wordinlist "$dev" "$devs2enable"; then
                     device_switch $dev off
+                fi
+            done
+        else
+            # start mode: enable listed radios
+            [ "$quiet" = "1" ] || printf "Enabling radios:"
+            for dev in bluetooth nfc wifi wwan; do
+                if wordinlist "$dev" "$devs2enable"; then
+                    [ "$quiet" = "1" ] || printf ' %s' "$dev"
+                    device_switch $dev on
                 fi
             done
             [ "$quiet" = "1" ] || echo "."
         fi
-
-        # enable configured radios
-        if [ -n "$devs2enable" ]; then
-            if [ "$1" = "radiosw" ]; then
-                # radiosw mode: disable radios not listed
-                for dev in bluetooth nfc wifi wwan; do
-                    if ! wordinlist "$dev" "$devs2enable"; then
-                        device_switch $dev off
-                    fi
-                done
-            else
-                # start mode: enable listed radios
-                [ "$quiet" = "1" ] || printf "Enabling radios:"
-                for dev in bluetooth nfc wifi wwan; do
-                    if wordinlist "$dev" "$devs2enable"; then
-                        [ "$quiet" = "1" ] || printf ' %s' "$dev"
-                        device_switch $dev on
-                    fi
-                done
-                [ "$quiet" = "1" ] || echo "."
-            fi
-        fi
-
-        # clean up: discard state file
-        rm -f "$RFSTATEFILE" 2> /dev/null
     fi
+
+    # clean up: discard state file
+    rm -f "$RFSTATEFILE" 2> /dev/null
 
     return 0
 }
